---
abstract: 'manage a Namecoin instance'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Signature: 0.66
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - Finance
  - Currency
  - Currancy
  - Namecoin
  - Micropayments
  - Commerce
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Namecoin
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.00
  Class::Accessor: 0.34
  JSON::RPC::Client: 0.93
  Scalar::Util: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Finance-Namecoin
  homepage: http://search.cpan.org/dist/Finance-Namecoin/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/Finance-Namecoin/
version: 0.002
